### ISSUE TITLE
End-to-end Testing

### ISSUE THREAD

**Issue by emizzle** [logos-storage/logos-storage-nim#279]
These issues are coordinated with work that Ben is doing for the testing.

Aiming for happy path. You create request, it's stored, if enough of the slots fail then request fails and you know about it but achieves the simple path of what we want to offer.

Test cases should include the following goals as part of the "happy path" w/ no edge cases:
- [ ] create a request and store it
- [ ] a slot is freed and there's an event
- [ ] request fails because too many slots are freed
- [ ] request expires
- [ ] host is paid for request

Working assumptions:
No ZKP for proving, validator checks for missed proof if message is > 0 then proof is received.

--Crete Off-site Additions--
- multinode and integration testing suite (eric) - 569 
- write additional integration tests (depends on multinode suite) (eric) - 570 
- integration test: verify validator function (adam) - 571
- react on transaction failures (eric) - 572
- obtain revert reason (eric) - 573
- merge incoming allowance (adam) - 574
- block TTL now + duration (adam) - 436
- Download only slot's data (mark) - 557
